version: 2.1
orbs:
  node: circleci/node@4.5.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
  build-and-deploy:
    docker:
      - image: cimg/node:12.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: zip
          command: zip -r function.zip .
      - aws-cli/setup:
          profile-name: sst_user
      - run: "aws lambda update-function-code --function-name SST_endpoint --zip-file fileb://function.zip"
workflows:
  test_and_deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - build-and-deploy:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
