version: 2.1
orbs:
  node: circleci/node@4.5.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy:
    docker:
      - image: cimg/node:12.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: zip
          command: zip -r function.zip .
      - aws-cli/setup:
          profile-name: volchenok
          run: "aws lambda update-function-code --function-name my-function --zip-file fileb://function.zip"
workflows:
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build
